version: '3'

services:
    php:
        container_name: php
        build:
            context: ./docker/php/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8000:80
        volumes:
            - ./php/:/var/www/html/
            
    db:
        container_name: database
        image: mysql:8.0.29
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: EdenAttack
        ports:
            - 8080:8080
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - EdenAttack

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5.2.0
        restart: always
        ports:
            - 8001:80
        environment:
            - PMA_HOST=db
        networks:
            - EdenAttack

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

volumes:
    db-data:

networks:
    EdenAttack:
